import mdx from "@astrojs/mdx";
import react from "@astrojs/react";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "astro/config";
import svgr from "vite-plugin-svgr";

import vercel from "@astrojs/vercel";

// NOTE: the sitemap is generated by prerendered endpoints
// (src/pages/sitemap-index.xml.ts + sitemap-0.xml.ts), NOT @astrojs/sitemap.
// The integration wrote its XML during astro:build:done, but the Vercel
// adapter's hook runs first (Astro unshifts the adapter) and packages
// .vercel/output/static before the files exist — so the sitemap never
// reached production.

export default defineConfig({
	site: "https://www.fusioncoreapps.com",
	trailingSlash: "never",
	i18n: {
		defaultLocale: "en",
		locales: ["en", "es", "pt"],
		routing: {
			prefixDefaultLocale: false,
		},
	},
	prefetch: {
		prefetchAll: true,
		defaultStrategy: "viewport",
	},
	integrations: [react(), mdx()],

	vite: {
		plugins: [tailwindcss(), svgr()],
	},
	adapter: vercel(),
});
